import pytest

from kevlar.preprocessing.normalizer import normalize
from kevlar.preprocessing.patterns import (
    ATTRIBUTION_PATTERN,
    CWD_PATTERN,
    DATE_CONTEXT_PATTERN,
    SYSTEM_REMINDER_PATTERN,
    TIMESTAMP_PATTERN,
)


class TestPatterns:
    def test_timestamp_iso(self):
        assert TIMESTAMP_PATTERN.search("Generated at 2026-03-21T14:30:00Z")

    def test_timestamp_offset(self):
        assert TIMESTAMP_PATTERN.search("time: 2026-03-21T14:30:00+05:00")

    def test_date_context(self):
        assert DATE_CONTEXT_PATTERN.search("Today's date is 2026-03-21.")

    def test_date_context_current(self):
        assert DATE_CONTEXT_PATTERN.search("currentDate\n2026-03-21")

    def test_system_reminder(self):
        text = "<system-reminder>some dynamic content here</system-reminder>"
        assert SYSTEM_REMINDER_PATTERN.search(text)

    def test_system_reminder_multiline(self):
        text = "<system-reminder>\nline1\nline2\n</system-reminder>"
        assert SYSTEM_REMINDER_PATTERN.search(text)

    def test_attribution(self):
        assert ATTRIBUTION_PATTERN.search("Generated by Claude Code v1.2.3")

    def test_cwd(self):
        assert CWD_PATTERN.search("working directory: /Users/user/project")


class TestNormalize:
    def test_disabled(self):
        result = normalize("system prompt", [{"role": "user", "content": "hello"}], enabled=False)
        assert result.system == "system prompt"
        assert result.messages == [{"role": "user", "content": "hello"}]

    def test_extracts_timestamp_from_system(self):
        system = "You are helpful. Generated at 2026-03-21T14:30:00Z. Be concise."
        result = normalize(system, [], enabled=True)
        assert "2026-03-21T14:30:00Z" not in result.system.split("[Dynamic Context]")[0]
        assert len(result.volatile_sections) > 0

    def test_extracts_system_reminder(self):
        system = "Instructions here.\n<system-reminder>Today is Thursday</system-reminder>\nMore instructions."
        result = normalize(system, [], enabled=True)
        stable_part = result.system.split("[Dynamic Context]")[0]
        assert "<system-reminder>" not in stable_part

    def test_stable_hash_unchanged_when_volatile_differs(self):
        system1 = "Be helpful.\nToday's date is 2026-03-21."
        system2 = "Be helpful.\nToday's date is 2026-03-22."
        r1 = normalize(system1, [], enabled=True)
        r2 = normalize(system2, [], enabled=True)
        assert r1.stable_hash == r2.stable_hash

    def test_message_content_normalized(self):
        messages = [{"role": "user", "content": "Check 2026-03-21T10:00:00Z for updates"}]
        result = normalize("system", messages, enabled=True)
        msg_content = result.messages[0]["content"]
        assert "2026-03-21T10:00:00Z" not in msg_content

    def test_preserves_non_text_blocks(self):
        messages = [{
            "role": "user",
            "content": [
                {"type": "text", "text": "hello 2026-03-21T10:00:00Z"},
                {"type": "tool_result", "tool_use_id": "123", "content": "result"},
            ],
        }]
        result = normalize("system", messages, enabled=True)
        blocks = result.messages[0]["content"]
        assert blocks[1]["type"] == "tool_result"

    def test_empty_system(self):
        result = normalize("", [], enabled=True)
        assert result.stable_hash
        assert result.volatile_sections == []
