import re

# Matches timestamps in various formats that Claude Code embeds
TIMESTAMP_PATTERN = re.compile(
    r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?\b"
)

# Matches "Today's date is YYYY-MM-DD" or similar
DATE_CONTEXT_PATTERN = re.compile(
    r"(?:Today'?s date is|current date[:\s]+|currentDate\n)\s*\d{4}-\d{2}-\d{2}\.?"
)

# Matches <system-reminder> blocks — these change between turns
SYSTEM_REMINDER_PATTERN = re.compile(
    r"<system-reminder>.*?</system-reminder>",
    re.DOTALL,
)

# Claude Code version/attribution headers
ATTRIBUTION_PATTERN = re.compile(
    r"(?:Generated by|Claude Code|claude-code)[^\n]*(?:v?\d+\.\d+[^\n]*)?",
    re.IGNORECASE,
)

# Working directory context that shifts between turns
CWD_PATTERN = re.compile(
    r"(?:working directory|cwd|current directory)[:\s]+[/\\]\S+",
    re.IGNORECASE,
)

# Git branch/status context
GIT_CONTEXT_PATTERN = re.compile(
    r"(?:current branch|git branch|on branch)[:\s]+\S+",
    re.IGNORECASE,
)

# File tree listings that change as user navigates
FILE_TREE_PATTERN = re.compile(
    r"(?:file tree|directory listing|project structure)[:\s]*\n(?:[ \t]*[├└│─\|+\-].*\n)*",
    re.IGNORECASE,
)

VOLATILE_PATTERNS = [
    TIMESTAMP_PATTERN,
    DATE_CONTEXT_PATTERN,
    SYSTEM_REMINDER_PATTERN,
    ATTRIBUTION_PATTERN,
    CWD_PATTERN,
    GIT_CONTEXT_PATTERN,
    FILE_TREE_PATTERN,
]
